### ISSUE TITLE
NoMethodError (undefined method `public_id' for "xxxx":String

### ISSUE THREAD

**Issue by ziaulrehman40** [ejschmitt/delayed_job_web#139]
As soon as i access the delayed_job end point i get this error

```
NoMethodError (undefined method `public_id' for "fffd0454ca1b6661bd671752c9f755fee6f14bf341229a4e0a60be55f06ab9d0":String

          session_data["session_id"] = sid.public_id
                                          ^^^^^^^^^^
Did you mean?  public_send):

actionpack (6.1.7.6) lib/action_dispatch/middleware/session/cookie_store.rb:105:in `write_session'
rack (2.2.8) lib/rack/session/abstract/id.rb:388:in `commit_session'
rack (2.2.8) lib/rack/session/abstract/id.rb:268:in `context'
rack (2.2.8) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/cookies.rb:697:in `call'
rack (2.2.8) lib/rack/method_override.rb:24:in `call'
rack-attack (6.7.0) lib/rack/attack.rb:127:in `call'
rack-cors (2.0.1) lib/rack/cors.rb:102:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.8) lib/rack/etag.rb:27:in `call'
rack (2.2.8) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.8) lib/rack/head.rb:12:in `call'
activerecord (6.1.7.6) lib/active_record/migration.rb:601:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.7.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.7.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
rollbar (3.4.0) lib/rollbar/middleware/rails/rollbar.rb:25:in `block in call'
rollbar (3.4.0) lib/rollbar.rb:145:in `scoped'
rollbar (3.4.0) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
rollbar (3.4.0) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
actionpack (6.1.7.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.7.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.7.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.7.6) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.7.6) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.7.6) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.7.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
rack-timeout (0.6.3) lib/rack/timeout/core.rb:148:in `block in call'
rack-timeout (0.6.3) lib/rack/timeout/support/timeout.rb:19:in `timeout'
rack-timeout (0.6.3) lib/rack/timeout/core.rb:147:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.7.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/host_authorization.rb:148:in `call'
apartment (1c6311f25f9c) lib/apartment/elevators/generic.rb:24:in `call'
railties (6.1.7.6) lib/rails/engine.rb:539:in `call'
puma (6.4.0) lib/puma/configuration.rb:272:in `call'
puma (6.4.0) lib/puma/request.rb:100:in `block in handle_request'
puma (6.4.0) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
puma (6.4.0) lib/puma/request.rb:99:in `handle_request'
puma (6.4.0) lib/puma/server.rb:443:in `process_client'
puma (6.4.0) lib/puma/server.rb:241:in `block in run'
puma (6.4.0) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

It kept working for some time, but not working now, trying to debug, will post updates here if i find a solution.

**Comment by ziaulrehman40** [comment]
Removed all custom middlewares being used, still getting the same error.

```
actionpack (6.1.7.6) lib/action_dispatch/middleware/session/cookie_store.rb:105:in `write_session'
rack (2.2.8) lib/rack/session/abstract/id.rb:388:in `commit_session'
rack (2.2.8) lib/rack/session/abstract/id.rb:268:in `context'
rack (2.2.8) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/cookies.rb:697:in `call'
rack (2.2.8) lib/rack/method_override.rb:24:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
rack (2.2.8) lib/rack/etag.rb:27:in `call'
rack (2.2.8) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.8) lib/rack/head.rb:12:in `call'
activerecord (6.1.7.6) lib/active_record/migration.rb:601:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.1.7.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (6.1.7.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.1.7.6) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.1.7.6) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.1.7.6) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (6.1.7.6) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (6.1.7.6) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (6.1.7.6) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.1.7.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/static.rb:24:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.1.7.6) lib/action_dispatch/middleware/host_authorization.rb:148:in `call'
railties (6.1.7.6) lib/rails/engine.rb:539:in `call'
puma (6.4.0) lib/puma/configuration.rb:272:in `call'
puma (6.4.0) lib/puma/request.rb:100:in `block in handle_request'
puma (6.4.0) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
puma (6.4.0) lib/puma/request.rb:99:in `handle_request'
puma (6.4.0) lib/puma/server.rb:443:in `process_client'
puma (6.4.0) lib/puma/server.rb:241:in `block in run'
puma (6.4.0) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by ziaulrehman40** [comment]
related: https://github.com/rails/rails/issues/38030

**Comment by ziaulrehman40** [comment]
Rotating secrets as mentioned in https://github.com/rails/rails/issues/38030#issuecomment-569333488 also didn't help
